interface Props { onLogin(): void; onRegister(): void; onStart(): void }

export function LandingPage({ onLogin, onRegister, onStart }: Props) {
  return <div className="landing"><header className="landing-header"><div className="landing-nav"><div className="brand"><span className="brand__mark" aria-hidden="true">N</span><span>Nutri-AI</span></div><nav aria-label="Navegação pública"><a href="#como-funciona">Como funciona</a><a href="#recursos">Recursos</a><button className="nav-button" type="button" onClick={onLogin}>Entrar</button><button className="button button--primary" type="button" onClick={onRegister}>Criar conta</button></nav></div></header>
    <main><section className="landing-hero"><div><p className="eyebrow">Nutrição para a vida real</p><h1>Um plano alimentar que cabe na sua rotina.</h1><p className="landing-hero__lead">Conte seus objetivos, preferências e orçamento. O Nutri-AI organiza um cardápio de sete dias e ajuda você a acompanhar sua evolução com clareza.</p><div className="landing-actions"><button className="button button--primary" type="button" onClick={onStart}>Começar gratuitamente</button><button className="button button--secondary" type="button" onClick={onLogin}>Já tenho uma conta</button></div><small>Comece sem cadastro. Três gerações gratuitas; crie sua conta somente quando quiser salvar e continuar.</small></div><div className="landing-plan" aria-label="Exemplo ilustrativo da organização do plano"><div className="landing-plan__top"><span>Uma semana organizada</span><strong>7 dias</strong></div><div className="landing-plan__day"><span>Manhã</span><strong>Café da manhã</strong><i/></div><div className="landing-plan__day"><span>Meio do dia</span><strong>Almoço</strong><i/></div><div className="landing-plan__day"><span>Noite</span><strong>Jantar</strong><i/></div><div className="landing-plan__footer"><span>Lista de compras</span><span>Orçamento semanal</span></div></div></section>
      <section className="landing-section" id="como-funciona"><div className="landing-section__heading"><p className="eyebrow">Como funciona</p><h2>Você informa. O Nutri-AI organiza. Você decide.</h2></div><ol className="landing-steps"><li><span>01</span><h3>Complete seu perfil</h3><p>Objetivo, rotina, preferências, restrições e orçamento ajudam a orientar seu plano.</p></li><li><span>02</span><h3>Solicite seu cardápio</h3><p>A IA prepara sete dias com refeições, estimativas nutricionais e lista de compras.</p></li><li><span>03</span><h3>Acompanhe sua evolução</h3><p>Registre seu peso e veja o histórico sem perder de vista o que funciona para você.</p></li></ol></section>
      <section className="landing-section landing-features" id="recursos"><div className="landing-section__heading"><p className="eyebrow">Dentro do produto</p><h2>Informação útil, sem transformar alimentação em complicação.</h2></div><div className="landing-feature-grid"><article><span>Plano</span><h3>Cardápio estruturado</h3><p>Refeições e preparo organizados em uma semana completa.</p></article><article><span>Compras</span><h3>Lista por categoria</h3><p>Ingredientes agrupados para facilitar a ida ao mercado.</p></article><article><span>Orçamento</span><h3>Custos estimados</h3><p>Uma referência para comparar o plano com seu orçamento semanal.</p></article><article><span>Evolução</span><h3>Histórico de peso</h3><p>Registros e visualização da variação ao longo do tempo.</p></article></div></section>
      <section className="landing-section landing-premium"><div><p className="eyebrow">Nutri-AI Premium</p><h2>Continue gerando quando os usos gratuitos terminarem.</h2><p>O acesso Premium libera novas gerações sem alterar seus registros gratuitos nem transformar administração em benefício comercial.</p></div><button className="button button--primary" type="button" onClick={onRegister}>Criar minha conta</button></section>
      <section className="landing-disclaimer"><strong>Uma ferramenta de organização, não um diagnóstico.</strong><p>As informações são estimativas e não substituem orientação individual de nutricionista ou médico.</p></section>
    </main><footer className="landing-footer"><div className="brand"><span className="brand__mark" aria-hidden="true">N</span><span>Nutri-AI</span></div><p>Planejamento alimentar e evolução em um só lugar.</p></footer></div>
}
